topics:
- /boson_camera_array/cam_1/image_raw
#- /boson_camera_array/cam_2/image_raw
#- /boson_camera_array/cam_3/image_raw
#- /boson_camera_array/cam_4/image_raw
#- /boson_camera_array/cam_5/image_raw
frequency: 4
viz : True
invert: False
start_time: 0 # in seconds
end_time:  120 # in seconds

