topics:
- /camera_array/cam0/image_raw
- /camera_array/cam1/image_raw
- /camera_array/cam2/image_raw
- /camera_array/cam3/image_raw
- /camera_array/cam4/image_raw
frequency: 3

start_time: 0 # in seconds
end_time: 10   # in seconds

