namespace: ['']
topic_list: 
#- [topic_name, message_type(as per dictionary), variable_name in mat file
 - [/imu/imu, sensor_msgs/Imu, imu_data]
 - [/sensor/xsens/sensor/imu_raw, sensor_msgs/Imu, xsens_imu_data]
 - [/android/tango1/imu_fixed, sensor_msgs/Imu, tango_imu_data]