topics:
- /boson_camera_array/cam0/image_raw
- /boson_camera_array/cam1/image_raw
- /boson_camera_array/cam2/image_raw
- /boson_camera_array/cam3/image_raw
- /boson_camera_array/cam4/image_raw

info_topics:
- /boson_camera_array/cam0/camera_info
- /boson_camera_array/cam1/camera_info
- /boson_camera_array/cam2/camera_info
- /boson_camera_array/cam3/camera_info
- /boson_camera_array/cam4/camera_info

img_type: jpg

frequency: 4

