namespace: seabed
topic_list: #- [topic_name, message_type(as per dictionary), variable_name in mat file
 - [/gps/odom, nav_msgs/Odometry, gps_odom]
 - [/dvl/odom, nav_msgs/Odometry, dvl_odom] 
 - [/imu/data, sensor_msgs/Imu, imu_data]
 - [/imu/data_raw, sensor_msgs/Imu, imu_data_raw]
 - [/cpu/temperature, std_msgs/Int8, cpu_temp]
 - [/heading, std_msgs/Float64, heading]
 - [/roll, std_msgs/Float64, roll]
 - [/pitch, std_msgs/Float64, pitch]
 - [/battery/temperature, std_msgs/Float64, battery_temp]
 - [/ct/conductivity, std_msgs/Float64, conductivity]
 - [/ct/salinity, std_msgs/Float64, salinity]
 - [/ct/temperature, std_msgs/Float64, ct_temp]
 - [/fins/elevator_cmd, std_msgs/Float64, elevator_cmd]
 - [/fins/roll_cmd, std_msgs/Float64, roll_cmd]
 - [/fins/rudder_cmd, std_msgs/Float64, rudder_cmd]
 - [/thruster/cmd, std_msgs/Float64, thruster_cmd]
 - [/paro/depth, std_msgs/Float64, depth]
 - [/paro/pressure, std_msgs/Float64, pressure]
 - [/battery/time_to_empty, std_msgs/Duration, time_to_empty]
 - [/battery/status, sensor_msgs/BatteryState, battery_state]
 - [/thruster/data, seabed_drivers/ThrusterData, thruster_data]

